server:
  port: 9191

spring:
 application:
    name: API-GATEWAY
 cloud:
     gateway:
       routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
         
          
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
         





management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
        
        
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2  





